apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gamania-app.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gamania-app
  template:
    metadata:
      labels:
        app: gamania-app
    spec:
      containers:
        - name: web-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /sre.txt
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
