apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamania-nginx-deployment
  labels:
    app: gamania-nginx 
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: gamania-nginx
  template:
    metadata:
      labels:
        app: gamania-nginx
    spec:
      containers:
        - name: gamania-app
          image: 694322569347.dkr.ecr.ap-southeast-1.amazonaws.com/gamania-nginx:v1 
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
